-- Import Supabase Materials into Cloudflare D1
-- Copy and paste this into Cloudflare Dashboard -> Storage & Databases -> D1 -> campusvault-db -> Console -> Execute

INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Integral Calculus', 'notes', 'Karan', 'NIT Patna', 'Engineering Mathematics II', 'Topics covers - Improper Integral - Leibnitz Theorem - Beta and Gamma Function - Double Integral', '2026-04-22', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776876991711_qg3b3n.pdf', 39, 8);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Introduction To Recursion', 'assignments', 'Karan', 'NIT Patna', 'Problem solving using C', '', '2026-04-16', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776313614689_lvcnhu.pdf', 5, 1);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('C - Programming', 'notes', 'Karan', 'NIT Patna', 'C - Programming', 'All basic topic cove in this notes', '2026-04-13', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776082211748_dzedi.pdf', 14, 4);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Electrochemistry', 'notes', 'Karan', 'NIT Patna', 'Engineering Chemistry', 'Some notes is missing so be careful', '2026-04-13', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776062273108_k0pn6o.pdf', 5, 1);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('General Organic Chemistry', 'notes', 'Karan', 'NIT Patna', 'Engineering Chemistry', '', '2026-04-20', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776661594568_dn3dx.pdf', 15, 4);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Probability', 'notes', 'Karan', 'NIT Patna', 'Engineering Mathematics', '', '2026-04-13', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776063040964_a1wu3b.pdf', 5, 1);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('He-Ne Laser and Ruby Laser', 'assignments', 'Karan', 'NIT Patna', 'Engineering Physics', 'Working Principle of He-Ne Laser and Ruby Laser', '2026-04-14', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776190383858_1nbel.pdf', 10, 2);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Mid Sem & End Sem Paper of Batch 2025', 'papers', 'Karan', 'NIT Patna', 'MAE Branch', '1st Semester Exam paper of 2025 Batch', '2026-04-16', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776314746976_vq9bgu.pdf', 10, 2);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Complex Analysis', 'notes', 'Karan', 'NIT Patna', 'Engineering Mathematics', 'Some question solution incomplete or error in calculation, So be careful', '2026-04-13', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776063948903_wqloba.pdf', 14, 3);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('End Semester of 1st semester', 'papers', 'Karan', 'NIT Patna', 'MAE Branch', 'All paper MAE of 1st semester of batch 2024', '2026-04-05', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1775403830894_7awex.pdf', 17, 4);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Coals and Electrochemistry', 'notes', 'Karan', 'NIT Patna', 'Engineering Chemistry', 'It is the combine notes of unit name Coal and Electrochemistry.', '2026-04-05', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1775402634232_ib9i2b.pdf', 36, 8);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Electrical Workshop Assignment', 'assignments', 'Karan', 'NIT Patna', 'Electrical Workshop', 'It is a assignment of Electrical Workshop that contains some questions and answers', '2026-05-02', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1777698901830_uy8kfb.pdf', 10, 2);
INSERT INTO materials (title, type, author, college, subject, description, date, fileName, rating_sum, rating_count) VALUES ('Chemical Bonding and Coordination Compounds', 'notes', 'Karan', 'NIT Patna', 'Engineering Chemistry', '', '2026-04-13', 'https://yrdwwkzgpklykbknhmck.supabase.co/storage/v1/object/public/uploads/1776061910117_18hjv8.pdf', 11, 3);
